function cfg = pfc_ml_config()
%PFC_ML_CONFIG Single source of truth for the Boost PFC ML project.
%
% This function only creates and validates a configuration structure.
% It does not load, simulate, modify, or save the Simulink model.
%
% Stage 7 architecture:
%   real Simulink design of experiments -> J surrogate regression
%   -> validation-only model selection -> condition-specific KP/KI search
%   -> held-out real Simulink validation. LHS creates input points only;
%   it never creates objectives, metrics, safety labels, or waveforms.
%
% MATLAB release: R2025a


%% ============================================================
% CONFIGURATION IDENTITY
%% ============================================================

cfg = struct();

cfg.Project.Name = ...
    'Boost PFC Supervised ML PI Auto-Tuner';

cfg.Project.ConfigVersion = '1.6.0';
cfg.Project.Stage = 7;
cfg.Project.RandomSeed = 42;
cfg.Project.MatlabRelease = 'R2025a';
cfg.Project.SimulationOnly = true;


%% ============================================================
% MODEL AND BLOCK PATHS
%% ============================================================

cfg.Model.Name = ...
    'Boost_PFC_BayesOpt_v1_WORKING_BASELINE';

cfg.Model.File = ...
    [cfg.Model.Name '.slx'];

cfg.Model.ExpectedSHA256 = ...
    ['fa14c2e42eadd74724da3f6c5687e4d7287584801a6cdeed38e0' ...
     'dc1e41fe551b'];

cfg.Model.ControllerBlock = ...
    [cfg.Model.Name '/STM32_PFC_Controller'];

cfg.Model.ACSourceBlock = ...
    [cfg.Model.Name '/AC Voltage Source'];

cfg.Model.BaseLoadBlock = ...
    [cfg.Model.Name '/Series RLC Branch2'];

cfg.Model.SwitchedLoadBlock = ...
    [cfg.Model.Name '/Series RLC Branch3'];

cfg.Model.BoostInductorBlock = ...
    [cfg.Model.Name '/Series RLC Branch1'];

cfg.Model.DCBusCapacitorBlock = ...
    [cfg.Model.Name '/Parallel RLC Branch1'];

cfg.Model.LoadSwitchBlock = ...
    [cfg.Model.Name '/IGBT'];

cfg.Model.LoadCommandSumBlock = ...
    [cfg.Model.Name '/Add'];

cfg.Model.LoadOnStepBlock = ...
    [cfg.Model.Name '/Step'];

cfg.Model.LoadOffStepBlock = ...
    [cfg.Model.Name '/Step2'];

cfg.Model.ScopeBlocks = string({ ...
    [cfg.Model.Name '/Scope']; ...
    [cfg.Model.Name '/Scope1']; ...
    [cfg.Model.Name '/Scope2']; ...
    [cfg.Model.Name '/Scope3']; ...
    [cfg.Model.Name '/Scope4']});

cfg.Model.RequiredLoggedSignals = string({ ...
    'VOUT_MON'; ...
    'IL_RAW'; ...
    'VAC_RAW'; ...
    'DUTY_MON'; ...
    'IREF_MON'});

cfg.Model.OptionalLoggedSignals = string({ ...
    'VIN_MON'; ...
    'IL_MON'});

cfg.Model.SignalLoggingName = 'logsout';
cfg.Model.FixedStep_s = 1e-7;
cfg.Model.DisableVisualizationDuringRuns = true;
cfg.Model.CloseEditorDuringRuns = true;
cfg.Model.NeverSaveBaseline = true;

% Low-disk signal-logging contract. The solver still executes at 1e-7 s;
% only the samples retained for metric calculation are decimated. Optional
% DUTY_MON and IREF_MON are additionally retained for Stage 7 safety and
% control-effort checks. Other optional monitors remain off.
cfg.Model.LowDiskLoggedSignalNames = string({ ...
    'VOUT_MON'; ...
    'IL_RAW'; ...
    'VAC_RAW'; ...
    'DUTY_MON'; ...
    'IREF_MON'});

cfg.Model.LowDiskLoggedBlockPaths = string({ ...
    cfg.Model.ControllerBlock; ...
    [cfg.Model.Name '/IL_MEAS']; ...
    [cfg.Model.Name '/VAC_MEAS']; ...
    cfg.Model.ControllerBlock; ...
    cfg.Model.ControllerBlock});

cfg.Model.LowDiskLoggedPortIndices = [6; 1; 1; 3; 4];

% VOUT: 2 MHz, IL: 5 MHz, VAC: 1 MHz effective logging rates.
% These remain above the 300 kHz power-quality analysis grid and preserve
% dense switching-cycle coverage while greatly reducing repository size.
cfg.Model.LowDiskLoggedDecimation = [5; 2; 10; 10; 10];


%% ============================================================
% LOW-DISK / TEMP REPOSITORY PROTECTION
%% ============================================================

cfg.Storage.LowDiskMode = true;
cfg.Storage.DisableUnusedModelOutputs = true;
cfg.Storage.ClearSDIRepositoryBeforeStage = true;
cfg.Storage.ClearSDIRepositoryBeforeEachRun = true;
cfg.Storage.ClearSDIRepositoryAfterEachRun = true;
cfg.Storage.MinimumFreeSpaceBeforeRun_GB = 10.0;
cfg.Storage.WarnBelowFreeSpace_GB = 20.0;
cfg.Storage.ExpectedMaximumRepository_GB = 1.0;


%% ============================================================
% PHYSICAL SYSTEM
%% ============================================================

cfg.Physical.RatedPower_W = 1400.0;
cfg.Physical.InputVoltageRange_Vrms = [180.0, 265.0];
cfg.Physical.LineFrequency_Hz = 50.0;
cfg.Physical.TargetVout_V = 400.0;
cfg.Physical.BoostInductance_H = 311e-6;
cfg.Physical.DCBusCapacitance_F = 2.0 * 680e-6;
cfg.Physical.SwitchingFrequency_Hz = 75e3;

% Stage 7 uses real parameter changes in the Simulink plant. These ranges
% represent inductance tolerance/temperature, DC-link capacitance tolerance
% and aging, and normal line-frequency variation.
cfg.Physical.BoostInductanceRange_H = ...
    [0.80, 1.20] * cfg.Physical.BoostInductance_H;
cfg.Physical.DCBusCapacitanceRange_F = ...
    [0.70, 1.10] * cfg.Physical.DCBusCapacitance_F;
cfg.Physical.LineFrequencyRange_Hz = [47.0, 53.0];


%% ============================================================
% CONTROLLER CONTRACT
%% ============================================================

% The baseline values are used as a known safe but non-optimal start.
cfg.Controller.BaselineKP = 0.010;
cfg.Controller.BaselineKI = 0.80;
cfg.Controller.BaselineIampMax_A = 14.0;

% The benchmark is for comparison/fallback only. It must never be used as
% a hidden constant output of the student model.
cfg.Controller.BenchmarkKP = 0.0599776526;
cfg.Controller.BenchmarkKI = 4.9870628691;
cfg.Controller.StrongFixedKP = 0.150;
cfg.Controller.StrongFixedKI = 12.00;

% The V6/V7 engineering correction is fixed. IAMP_MAX is not an ML output
% and is not a BayesOpt variable.
cfg.Controller.FixedIampMax_A = 16.0;
cfg.Controller.ControllerAbsoluteCurrentLimit_A = 18.0;
cfg.Controller.DutyMaximum = 0.85;

cfg.Controller.KPVariableName = 'KP_V';
cfg.Controller.KIVariableName = 'KI_V';
cfg.Controller.IampVariableName = 'IAMP_MAX';


%% ============================================================
% GAIN DOMAINS
%% ============================================================

% This is the first, previously exercised domain. Pilot data generation
% starts here.
cfg.Gains.PilotKPBounds = [0.010, 0.060];
cfg.Gains.PilotKIBounds = [0.80, 5.00];

% The previous optimum was close to both upper bounds. These expanded
% bounds are therefore recorded for a later boundary-sensitivity test.
% They must not be used until Stage 4 safety/objective tests pass.
cfg.Gains.ExpandedKPBounds = [0.006, 0.080];
cfg.Gains.ExpandedKIBounds = [0.50, 7.00];

% Stage 5C-validated protected envelope. Stage 6 uses it as the pilot
% teacher-search domain. ML training is still conditional on the Stage 6
% boundary-hit and teacher-diversity gates.
cfg.Gains.OuterProbeKPBounds = [0.006, 0.100];
cfg.Gains.OuterProbeKIBounds = [0.50, 9.00];

% Stage 6B is diagnostic only. It tests whether the Stage 6 labels were
% right-censored by the previous upper bounds; it does not authorize ML
% training and it does not change the protected baseline model.
cfg.Gains.BoundaryProbeKPBounds = [0.006, 0.150];
cfg.Gains.BoundaryProbeKIBounds = [0.50, 12.00];

cfg.Gains.SamplingScale = 'log';

% Student predictions are clamped before validation. These bounds do not
% make a prediction safe; every prediction still requires Simulink proof.
cfg.Gains.PredictionKPBounds = cfg.Gains.BoundaryProbeKPBounds;
cfg.Gains.PredictionKIBounds = cfg.Gains.BoundaryProbeKIBounds;

% Limit a single student correction to a factor of 3 in either direction.
cfg.Gains.MaximumAbsoluteDeltaLog = log(3.0);


%% ============================================================
% DYNAMIC-LOAD TEST PROFILE
%% ============================================================

% Short diagnostic/teacher profile. It preserves the proven 0.6/1.0 s
% load transitions and leaves 0.4 s before/after each transition.
cfg.Profile.Diagnostic.StartTime_s = 0.0;
cfg.Profile.Diagnostic.LoadOnTime_s = 0.60;
cfg.Profile.Diagnostic.LoadOffTime_s = 1.00;
cfg.Profile.Diagnostic.StopTime_s = 1.40;

% Long profile is reserved for final robustness validation.
cfg.Profile.LongValidation.StartTime_s = 0.0;
cfg.Profile.LongValidation.LoadOnTime_s = 0.60;
cfg.Profile.LongValidation.LoadOffTime_s = 1.80;
cfg.Profile.LongValidation.StopTime_s = 2.20;

cfg.Profile.StepBefore = 0.0;
cfg.Profile.LoadOnStepAfter = 1.0;
cfg.Profile.LoadOffStepAfter = -1.0;

% Metric windows are expressed relative to load transition times.
cfg.Profile.Metrics.PreLoadWindow_s = [-0.20, -0.02];
cfg.Profile.Metrics.EarlyHighWindow_s = [0.05, 0.20];
cfg.Profile.Metrics.LateHighWindow_s = [-0.20, -0.02];
cfg.Profile.Metrics.PostLoadWindow_s = [0.05, 0.30];
cfg.Profile.Metrics.SettlingBand_V = 8.0;
cfg.Profile.Metrics.SettlingHold_s = 0.04;
cfg.Profile.Metrics.LineCyclesForPowerQuality = 10;
cfg.Profile.Metrics.UniformSampleRate_Hz = 300e3;
cfg.Profile.Metrics.THDMaximumHarmonic = 40;


%% ============================================================
% LOAD PARAMETERIZATION
%% ============================================================

% At 400 V: R = V^2/P. The switched resistor supplies only DeltaP.
cfg.Load.NominalPreLoad_W = 300.0;
cfg.Load.NominalHighLoad_W = 1400.0;
cfg.Load.NominalDeltaPower_W = ...
    cfg.Load.NominalHighLoad_W - cfg.Load.NominalPreLoad_W;

cfg.Load.ExpectedBaseResistance_Ohm = 533.3;
cfg.Load.ExpectedSwitchedResistance_Ohm = 145.0;

cfg.Load.ScenarioPreLoadRange_W = [200.0, 500.0];
cfg.Load.ScenarioHighLoadRange_W = [900.0, 1400.0];
cfg.Load.MinimumLoadStep_W = 500.0;

cfg.Load.BaseResistanceFormula = 'TargetVout^2 / PreLoadPower';
cfg.Load.SwitchedResistanceFormula = ...
    'TargetVout^2 / (HighLoadPower - PreLoadPower)';


%% ============================================================
% OBJECTIVE FUNCTION BASELINE
%% ============================================================

% The weights are an engineering baseline, not universal truth. Stage 4
% must prove sensible good/bad ordering and later sensitivity analysis
% must report whether conclusions depend strongly on these weights.
cfg.Objective.TermNames = string({ ...
    'SteadyError'; ...
    'LoadOnUndershoot'; ...
    'LoadOffOvershoot'; ...
    'SettlingTime'; ...
    'TransientMAE'; ...
    'HighLoadRipple'; ...
    'THD'; ...
    'PowerFactorError'});

cfg.Objective.Weights = [ ...
    0.12; ...
    0.18; ...
    0.12; ...
    0.15; ...
    0.10; ...
    0.08; ...
    0.15; ...
    0.10];

cfg.Objective.Normalization.SteadyError_V = 10.0;
cfg.Objective.Normalization.LoadOnUndershoot_V = 100.0;
cfg.Objective.Normalization.LoadOffOvershoot_V = 60.0;
cfg.Objective.Normalization.SettlingTime_s = 0.40;
cfg.Objective.Normalization.TransientMAE_V = 30.0;
cfg.Objective.Normalization.HighLoadRipple_Vpp = 30.0;
cfg.Objective.Normalization.THD_Percent = 20.0;
cfg.Objective.Normalization.PowerFactorError = 0.15;

cfg.Objective.FailedSimulationPenalty = 1e6;
cfg.Objective.ComputeOnlyForSafeRuns = true;


%% ============================================================
% HARD SAFETY GATES
%% ============================================================

% Safety gates are separate from the soft performance objective.
cfg.Safety.RequireSimulationSuccess = true;
cfg.Safety.LateHighLoadVoutRange_V = [392.0, 408.0];
cfg.Safety.GlobalVoutMinimum_V = 300.0;
cfg.Safety.GlobalVoutMaximum_V = 431.0;
cfg.Safety.InductorPeakMaximum_A = 16.0;
cfg.Safety.PowerFactorMinimum = 0.95;
cfg.Safety.THDMaximum_Percent = 15.0;
cfg.Safety.RequireFiniteMetrics = true;

% Control-command gates are measured directly from Simulink logs. They
% detect invalid controller commands independently of plant-output gates.
cfg.Safety.DutyCommandTolerance = 1e-6;
cfg.Safety.IrefCommandTolerance_A = 0.20;


%% ============================================================
% STAGE 6B BOUNDARY / CONTROL-EFFORT DIAGNOSTIC
%% ============================================================

cfg.Stage6B.KPExtended = 0.150;
cfg.Stage6B.KIExtended = 12.00;
cfg.Stage6B.KPMid = 0.125;
cfg.Stage6B.KIMid = 10.50;
cfg.Stage6B.PointNames = string({ ...
    'CURRENT'; ...
    'KP_EXTENDED'; ...
    'KI_EXTENDED'; ...
    'BOTH_MID'; ...
    'BOTH_EXTENDED'});
cfg.Stage6B.PointsPerScenario = 5;
cfg.Stage6B.ExpectedRunCount = 30;
cfg.Stage6B.ImprovementThresholdPercent = 2.0;
cfg.Stage6B.DutySaturationThresholdFraction = 0.98;
cfg.Stage6B.IrefSaturationThresholdFraction = 0.98;


%% ============================================================
% STAGE 7 REAL-SIMULATION SURROGATE-ML PILOT
%% ============================================================

% Fifteen independent physical scenarios are split by ScenarioID. Six
% controller points per scenario produce 90 genuine Simulink-labelled rows.
cfg.Stage7.ScenarioCount = 15;
cfg.Stage7.GainPointsPerScenario = 6;
cfg.Stage7.ExpectedDatasetRuns = 90;
cfg.Stage7.TrainScenarioCount = 10;
cfg.Stage7.ValidationScenarioCount = 2;
cfg.Stage7.TestScenarioCount = 3;
cfg.Stage7.RecommendationGridSize = 45;
cfg.Stage7.RevalidateTestRecommendations = true;
cfg.Stage7.MinimumSafeTrainingRows = 40;
cfg.Stage7.MaximumAcceptableMedianTestRegret = 0.20;
cfg.Stage7.MaximumAcceptableTestSafetyViolations = 0;
cfg.Stage7.ResponseTransform = 'log';
cfg.Stage7.CandidateModels = string({ ...
    'GaussianProcessRegression'; ...
    'BoostedRegressionTrees'});
cfg.Stage7.PredictorNames = string({ ...
    'Vin_RMS'; ...
    'Pload_Pre_W'; ...
    'Pload_High_W'; ...
    'BoostInductance_uH'; ...
    'DCBusCapacitance_uF'; ...
    'LineFrequency_Hz'; ...
    'LogKP'; ...
    'LogKI'});


%% ============================================================
% SCENARIO DESIGN
%% ============================================================

cfg.Scenarios.InputVoltageRange_Vrms = ...
    cfg.Physical.InputVoltageRange_Vrms;

cfg.Scenarios.PilotInputVoltages_Vrms = ...
    [180.0, 195.0, 215.0, 230.0, 247.0, 265.0];

cfg.Scenarios.PilotCount = 6;
cfg.Scenarios.FinalMinimumCount = 30;
cfg.Scenarios.FinalTargetCount = 36;
cfg.Scenarios.FinalMaximumCount = 40;

cfg.Scenarios.SplitFractions = [0.70, 0.15, 0.15];
cfg.Scenarios.SplitNames = string({'train', 'validation', 'test'});
cfg.Scenarios.SplitUnit = 'ScenarioID';
cfg.Scenarios.ForbidRowWiseRandomSplit = true;
cfg.Scenarios.RequireDisjointScenarioIDs = true;


%% ============================================================
% BAYESOPT TEACHER
%% ============================================================

cfg.Teacher.Method = 'BayesianOptimization';
cfg.Teacher.PilotEvaluationsPerScenario = 8;
cfg.Teacher.FinalEvaluationsPerScenario = 12;
cfg.Teacher.AcquisitionFunctionName = ...
    'expected-improvement-plus';
cfg.Teacher.IsObjectiveDeterministic = true;
cfg.Teacher.UseParallel = false;
cfg.Teacher.Verbose = 1;
cfg.Teacher.SaveEverySuccessfulEvaluation = true;
cfg.Teacher.ResumeFromCheckpoint = true;
cfg.Teacher.RevalidateBestPoint = true;
cfg.Teacher.KeepUnsafeAndFailedRows = true;
cfg.Teacher.UseUnsafeRowsForStudentRegression = false;

% Stage 6 is a pilot gate, not automatic permission to train. If the
% teacher optima collapse to one boundary point, gain scheduling has not
% yet been justified and the pipeline must stop before student training.
cfg.Teacher.MinimumSafeEvaluationsPerScenario = 2;
cfg.Teacher.MinimumRegressionRowsPerScenario = 2;
cfg.Teacher.BoundaryHitRelativeTolerance = 0.02;
cfg.Teacher.MaximumBoundaryHitFractionForTraining = 0.50;
cfg.Teacher.MinimumUniqueTeacherGainPairs = 3;
cfg.Teacher.MinimumTeacherLogSpan = log(1.15);


%% ============================================================
% DATASET SCHEMA
%% ============================================================

cfg.Data.IdentityColumns = string({ ...
    'ScenarioID'; ...
    'RunID'; ...
    'RandomSeed'; ...
    'Split'});

cfg.Data.ConditionColumns = string({ ...
    'Vin_RMS'; ...
    'Pload_Pre_W'; ...
    'Pload_High_W'; ...
    'DeltaP_W'; ...
    'LoadOnTime_s'; ...
    'LoadOffTime_s'});

cfg.Data.CurrentControllerColumns = string({ ...
    'CurrentKP'; ...
    'CurrentKI'; ...
    'LogCurrentKP'; ...
    'LogCurrentKI'});

cfg.Data.MetricColumns = string({ ...
    'PreLoadMean_V'; ...
    'HighLoadMean_V'; ...
    'PostLoadMean_V'; ...
    'SteadyStateError_V'; ...
    'LoadOnUndershoot_V'; ...
    'LoadOffOvershoot_V'; ...
    'LoadOnSettling_s'; ...
    'LoadOffSettling_s'; ...
    'LoadOnSettled'; ...
    'LoadOffSettled'; ...
    'HighLoadRipple_Vpp'; ...
    'GlobalVoutMinimum_V'; ...
    'GlobalVoutMaximum_V'; ...
    'ILPeak_A'; ...
    'PowerFactor'; ...
    'THD_Percent'; ...
    'InputPower_W'});

cfg.Data.StatusColumns = string({ ...
    'SimulationSucceeded'; ...
    'SafetyPassed'; ...
    'Objective'; ...
    'ElapsedTime_s'; ...
    'ErrorIdentifier'; ...
    'ErrorMessage'});

cfg.Data.TeacherLabelColumns = string({ ...
    'TeacherBestKP'; ...
    'TeacherBestKI'; ...
    'TeacherBestObjective'; ...
    'DeltaLogKP'; ...
    'DeltaLogKI'});

% Deliberately excluded from the first student predictor matrix:
%   Objective, TeacherBestKP, TeacherBestKI, DeltaLogKP, DeltaLogKI,
%   ScenarioID, RunID, ErrorIdentifier, ErrorMessage.
cfg.Data.StudentPredictorColumns = [ ...
    cfg.Data.ConditionColumns; ...
    cfg.Data.CurrentControllerColumns; ...
    cfg.Data.MetricColumns];

cfg.Data.StudentResponseColumns = string({ ...
    'DeltaLogKP'; ...
    'DeltaLogKI'});


%% ============================================================
% STUDENT MODEL CANDIDATES
%% ============================================================

cfg.Student.CandidateModels = string({ ...
    'LinearRegression'; ...
    'GaussianProcessRegression'; ...
    'BoostedRegressionTrees'; ...
    'BaggedRegressionTrees'});

cfg.Student.TrainSeparateKPAndKIModels = true;
cfg.Student.StandardizeNumericPredictors = true;
cfg.Student.RemoveZeroVariancePredictors = true;
cfg.Student.SelectionMetric = 'ValidationSimulinkRegret';
cfg.Student.UseTestSetForModelSelection = false;
cfg.Student.RequireSimulinkValidation = true;
cfg.Student.FallbackToBenchmarkAfterUnsafePrediction = true;


%% ============================================================
% SUCCESS CRITERIA
%% ============================================================

cfg.Success.MaximumTestSafetyViolationRate = 0.0;
cfg.Success.MinimumImprovedScenarioFraction = 0.90;
cfg.Success.MaximumMedianTeacherRegret = 0.10;
cfg.Success.MaximumP90TeacherRegret = 0.20;
cfg.Success.MinimumSimulationReductionFraction = 0.80;


%% ============================================================
% OUTPUT FILES AND CHECKPOINTING
%% ============================================================

% Keep low-disk Stage 6 checkpoints separate from the earlier full-rate
% attempt. Mixing old and decimated measurements in one teacher trace would
% weaken reproducibility, so this revision starts a clean output lineage.
cfg.Files.RootOutputFolder = 'pfc_ml_outputs_stage7_v160';
cfg.Files.Stage7CheckpointMAT = ...
    'pfc_ml_stage7_real_dataset_checkpoint.mat';
cfg.Files.Stage7DatasetMAT = 'pfc_ml_stage7_real_dataset.mat';
cfg.Files.Stage7DatasetCSV = 'pfc_ml_stage7_real_dataset.csv';
cfg.Files.Stage7ScenarioCSV = 'pfc_ml_stage7_scenarios.csv';
cfg.Files.Stage7ModelMAT = 'pfc_ml_stage7_surrogate_models.mat';
cfg.Files.Stage7ValidationCSV = ...
    'pfc_ml_stage7_heldout_validation.csv';
cfg.Files.Stage7SummaryMAT = 'pfc_ml_stage7_summary.mat';
cfg.Files.Stage6InputFolder = 'pfc_ml_outputs_low_disk_v140';
cfg.Files.Stage6SummaryCSV = 'pfc_ml_stage6_pilot_summary.csv';
cfg.Files.Stage6BBoundaryCheckpointMAT = ...
    'pfc_ml_stage6b_boundary_control_checkpoint.mat';
cfg.Files.Stage6BBoundaryResultsCSV = ...
    'pfc_ml_stage6b_boundary_control_results.csv';
cfg.Files.Stage6BBoundaryResultsMAT = ...
    'pfc_ml_stage6b_boundary_control_results.mat';
cfg.Files.Stage6BBoundarySummaryCSV = ...
    'pfc_ml_stage6b_boundary_control_summary.csv';
cfg.Files.PilotDatasetMAT = 'pfc_ml_pilot_dataset.mat';
cfg.Files.PilotDatasetCSV = 'pfc_ml_pilot_dataset.csv';
cfg.Files.PilotCheckpointMAT = 'pfc_ml_pilot_checkpoint.mat';
cfg.Files.FinalDatasetMAT = 'pfc_ml_final_dataset.mat';
cfg.Files.FinalDatasetCSV = 'pfc_ml_final_dataset.csv';
cfg.Files.FinalCheckpointMAT = 'pfc_ml_final_checkpoint.mat';
cfg.Files.ScenarioSplitMAT = 'pfc_ml_scenario_split.mat';
cfg.Files.StudentModelMAT = 'pfc_ml_student_models.mat';
cfg.Files.FinalResultsMAT = 'pfc_ml_final_results.mat';
cfg.Files.FinalResultsCSV = 'pfc_ml_final_results.csv';


%% ============================================================
% VALIDATE CONFIGURATION
%% ============================================================

validatePFCMLConfig(cfg);

fprintf('\n');
fprintf('====================================================\n');
fprintf('PFC ML CONFIGURATION VALIDATION: PASS\n');
fprintf('Config version       : %s\n', cfg.Project.ConfigVersion);
fprintf('Baseline protected   : %d\n', cfg.Model.NeverSaveBaseline);
fprintf('Scope crash guard    : %d\n', ...
    cfg.Model.DisableVisualizationDuringRuns);
fprintf('Fixed IAMP_MAX       : %.3f A\n', ...
    cfg.Controller.FixedIampMax_A);
fprintf('Objective weight sum : %.12f\n', ...
    sum(cfg.Objective.Weights));
fprintf('Predictor leakage    : NONE\n');
fprintf('Stage 7 real dataset: %d x %d = %d simulations\n', ...
    cfg.Stage7.ScenarioCount, cfg.Stage7.GainPointsPerScenario, ...
    cfg.Stage7.ExpectedDatasetRuns);
fprintf('Scenario split       : %d / %d / %d scenarios\n', ...
    cfg.Stage7.TrainScenarioCount, ...
    cfg.Stage7.ValidationScenarioCount, ...
    cfg.Stage7.TestScenarioCount);
fprintf('Physical variation   : Vin/load/L/C/fline\n');
fprintf('ML models            : GPR + boosted trees\n');
fprintf('Low-disk logging     : ON (VOUT/IL/VAC/DUTY/IREF)\n');
fprintf('Logging decimation   : %d / %d / %d / %d / %d\n', ...
    cfg.Model.LowDiskLoggedDecimation(1), ...
    cfg.Model.LowDiskLoggedDecimation(2), ...
    cfg.Model.LowDiskLoggedDecimation(3), ...
    cfg.Model.LowDiskLoggedDecimation(4), ...
    cfg.Model.LowDiskLoggedDecimation(5));
fprintf('SDI cleanup/run      : %d\n', ...
    cfg.Storage.ClearSDIRepositoryAfterEachRun);
fprintf('Simulation executed  : NO\n');
fprintf('Model modified       : NO\n');
fprintf('====================================================\n\n');

end


%% ============================================================
% LOCAL VALIDATION FUNCTION
%% ============================================================

function validatePFCMLConfig(cfg)

assert(cfg.Project.SimulationOnly, ...
    'PFCMLConfig:HardwareUseForbidden', ...
    'This project configuration must remain simulation-only.');

assert(cfg.Model.NeverSaveBaseline, ...
    'PFCMLConfig:BaselineProtectionDisabled', ...
    'NeverSaveBaseline must remain true.');

assert(cfg.Model.DisableVisualizationDuringRuns, ...
    'PFCMLConfig:ScopeProtectionDisabled', ...
    'Visualization blocks must be disabled during automated runs.');

assert(cfg.Storage.LowDiskMode && ...
       cfg.Storage.ClearSDIRepositoryBeforeEachRun && ...
       cfg.Storage.ClearSDIRepositoryAfterEachRun, ...
    'PFCMLConfig:LowDiskProtectionDisabled', ...
    'Low-disk mode and per-run SDI cleanup must remain enabled.');

assert(numel(cfg.Model.LowDiskLoggedSignalNames) == 5 && ...
       numel(cfg.Model.LowDiskLoggedBlockPaths) == 5 && ...
       numel(cfg.Model.LowDiskLoggedPortIndices) == 5 && ...
       numel(cfg.Model.LowDiskLoggedDecimation) == 5, ...
    'PFCMLConfig:LowDiskLoggingShapeInvalid', ...
    'Stage 7 low-disk logging must contain exactly five signals.');

assert(isequal(cfg.Model.LowDiskLoggedSignalNames(:), ...
        cfg.Model.RequiredLoggedSignals(:)), ...
    'PFCMLConfig:RequiredLoggingMismatch', ...
    ['Low-disk logging must retain VOUT_MON, IL_RAW, VAC_RAW, ' ...
     'DUTY_MON, and IREF_MON.']);

assert(all(cfg.Model.LowDiskLoggedPortIndices >= 1) && ...
       all(mod(cfg.Model.LowDiskLoggedPortIndices, 1) == 0) && ...
       all(cfg.Model.LowDiskLoggedDecimation >= 1) && ...
       all(mod(cfg.Model.LowDiskLoggedDecimation, 1) == 0), ...
    'PFCMLConfig:LowDiskLoggingValuesInvalid', ...
    'Logging port indices and decimation factors must be positive integers.');

assert(cfg.Storage.MinimumFreeSpaceBeforeRun_GB >= 5.0 && ...
       cfg.Storage.WarnBelowFreeSpace_GB >= ...
           cfg.Storage.MinimumFreeSpaceBeforeRun_GB, ...
    'PFCMLConfig:DiskThresholdInvalid', ...
    'Low-disk warning and stop thresholds are invalid.');

assert(abs(sum(cfg.Objective.Weights) - 1.0) < 1e-12, ...
    'PFCMLConfig:ObjectiveWeightsInvalid', ...
    'Objective weights must sum to exactly 1.0.');

assert(numel(cfg.Objective.TermNames) == ...
        numel(cfg.Objective.Weights), ...
    'PFCMLConfig:ObjectiveTermCountMismatch', ...
    'Each objective term must have exactly one weight.');

assert(all(cfg.Objective.Weights >= 0.0), ...
    'PFCMLConfig:NegativeObjectiveWeight', ...
    'Objective weights cannot be negative.');

assert(cfg.Controller.FixedIampMax_A <= ...
        cfg.Controller.ControllerAbsoluteCurrentLimit_A, ...
    'PFCMLConfig:CurrentLimitConflict', ...
    'Fixed IAMP_MAX exceeds the absolute controller current limit.');

assert(cfg.Safety.InductorPeakMaximum_A <= ...
        cfg.Controller.ControllerAbsoluteCurrentLimit_A, ...
    'PFCMLConfig:SafetyCurrentLimitConflict', ...
    'Safety peak-current gate exceeds the controller absolute limit.');

assert(cfg.Gains.PilotKPBounds(1) > 0.0 && ...
       cfg.Gains.PilotKIBounds(1) > 0.0, ...
    'PFCMLConfig:NonpositiveGainBound', ...
    'Log-sampled gain bounds must be strictly positive.');

assert(all(cfg.Gains.PilotKPBounds > 0.0) && ...
       all(cfg.Gains.PilotKIBounds > 0.0) && ...
       all(cfg.Gains.ExpandedKPBounds > 0.0) && ...
       all(cfg.Gains.ExpandedKIBounds > 0.0) && ...
       all(cfg.Gains.OuterProbeKPBounds > 0.0) && ...
       all(cfg.Gains.OuterProbeKIBounds > 0.0) && ...
       all(cfg.Gains.BoundaryProbeKPBounds > 0.0) && ...
       all(cfg.Gains.BoundaryProbeKIBounds > 0.0), ...
    'PFCMLConfig:InvalidLogGainDomain', ...
    'Every log-domain gain bound must be strictly positive.');

assert(cfg.Gains.PilotKPBounds(1) < ...
       cfg.Gains.PilotKPBounds(2) && ...
       cfg.Gains.PilotKIBounds(1) < ...
       cfg.Gains.PilotKIBounds(2), ...
    'PFCMLConfig:InvalidPilotBounds', ...
    'Pilot gain bounds must be strictly increasing.');

assert(cfg.Gains.ExpandedKPBounds(1) < ...
       cfg.Gains.ExpandedKPBounds(2) && ...
       cfg.Gains.ExpandedKIBounds(1) < ...
       cfg.Gains.ExpandedKIBounds(2), ...
    'PFCMLConfig:InvalidExpandedBounds', ...
    'Expanded gain bounds must be strictly increasing.');

assert(cfg.Gains.OuterProbeKPBounds(1) < ...
       cfg.Gains.OuterProbeKPBounds(2) && ...
       cfg.Gains.OuterProbeKIBounds(1) < ...
       cfg.Gains.OuterProbeKIBounds(2), ...
    'PFCMLConfig:InvalidOuterProbeBounds', ...
    'Outer-probe gain bounds must be strictly increasing.');

assert(cfg.Gains.OuterProbeKPBounds(2) >= ...
       cfg.Gains.ExpandedKPBounds(2) && ...
       cfg.Gains.OuterProbeKIBounds(2) >= ...
       cfg.Gains.ExpandedKIBounds(2), ...
    'PFCMLConfig:OuterProbeDoesNotExpandDomain', ...
    'Outer-probe bounds must include the Stage 5B expanded maxima.');

assert(cfg.Gains.BoundaryProbeKPBounds(1) < ...
       cfg.Gains.BoundaryProbeKPBounds(2) && ...
       cfg.Gains.BoundaryProbeKIBounds(1) < ...
       cfg.Gains.BoundaryProbeKIBounds(2) && ...
       cfg.Gains.BoundaryProbeKPBounds(2) >= ...
           cfg.Gains.OuterProbeKPBounds(2) && ...
       cfg.Gains.BoundaryProbeKIBounds(2) >= ...
           cfg.Gains.OuterProbeKIBounds(2), ...
    'PFCMLConfig:InvalidBoundaryProbeBounds', ...
    'Stage 6B bounds must include and extend the Stage 6 domain.');

assert(cfg.Stage6B.PointsPerScenario == ...
       numel(cfg.Stage6B.PointNames) && ...
       cfg.Stage6B.ExpectedRunCount == ...
           cfg.Scenarios.PilotCount * cfg.Stage6B.PointsPerScenario && ...
       cfg.Stage6B.KPExtended == cfg.Gains.BoundaryProbeKPBounds(2) && ...
       cfg.Stage6B.KIExtended == cfg.Gains.BoundaryProbeKIBounds(2) && ...
       cfg.Stage6B.ImprovementThresholdPercent > 0.0, ...
    'PFCMLConfig:InvalidStage6BDesign', ...
    'Stage 6B point count, bounds, or improvement gate is invalid.');

assert(cfg.Controller.DutyMaximum > 0.0 && ...
       cfg.Controller.DutyMaximum <= 1.0 && ...
       cfg.Safety.DutyCommandTolerance >= 0.0 && ...
       cfg.Safety.IrefCommandTolerance_A >= 0.0 && ...
       cfg.Stage6B.DutySaturationThresholdFraction > 0.0 && ...
       cfg.Stage6B.DutySaturationThresholdFraction <= 1.0 && ...
       cfg.Stage6B.IrefSaturationThresholdFraction > 0.0 && ...
       cfg.Stage6B.IrefSaturationThresholdFraction <= 1.0, ...
    'PFCMLConfig:InvalidControlDiagnosticGate', ...
    'Stage 6B control-command limits or saturation gates are invalid.');

assert(cfg.Stage7.ExpectedDatasetRuns == ...
       cfg.Stage7.ScenarioCount * cfg.Stage7.GainPointsPerScenario && ...
       cfg.Stage7.ScenarioCount == ...
           cfg.Stage7.TrainScenarioCount + ...
           cfg.Stage7.ValidationScenarioCount + ...
           cfg.Stage7.TestScenarioCount && ...
       cfg.Stage7.TrainScenarioCount >= 5 && ...
       cfg.Stage7.ValidationScenarioCount >= 1 && ...
       cfg.Stage7.TestScenarioCount >= 2, ...
    'PFCMLConfig:InvalidStage7Design', ...
    'Stage 7 run count or grouped scenario split is invalid.');

assert(cfg.Stage7.RecommendationGridSize >= 10 && ...
       cfg.Stage7.MinimumSafeTrainingRows >= 20 && ...
       cfg.Stage7.MinimumSafeTrainingRows <= ...
           cfg.Stage7.TrainScenarioCount * ...
           cfg.Stage7.GainPointsPerScenario && ...
       cfg.Stage7.MaximumAcceptableMedianTestRegret >= 0.0, ...
    'PFCMLConfig:InvalidStage7MLGate', ...
    'Stage 7 grid size, training-row gate, or regret gate is invalid.');

assert(cfg.Physical.BoostInductanceRange_H(1) > 0.0 && ...
       cfg.Physical.BoostInductanceRange_H(1) < ...
           cfg.Physical.BoostInductanceRange_H(2) && ...
       cfg.Physical.DCBusCapacitanceRange_F(1) > 0.0 && ...
       cfg.Physical.DCBusCapacitanceRange_F(1) < ...
           cfg.Physical.DCBusCapacitanceRange_F(2) && ...
       cfg.Physical.LineFrequencyRange_Hz(1) < ...
           cfg.Physical.LineFrequencyRange_Hz(2), ...
    'PFCMLConfig:InvalidStage7PhysicalRanges', ...
    'Stage 7 L/C/line-frequency ranges are invalid.');

assert(cfg.Teacher.MinimumSafeEvaluationsPerScenario >= 1 && ...
       cfg.Teacher.MinimumSafeEvaluationsPerScenario <= ...
           cfg.Teacher.PilotEvaluationsPerScenario, ...
    'PFCMLConfig:InvalidSafeEvaluationGate', ...
    'The safe-evaluation gate must fit inside the pilot budget.');

assert(cfg.Teacher.MinimumRegressionRowsPerScenario >= 1 && ...
       cfg.Teacher.MinimumRegressionRowsPerScenario <= ...
           cfg.Teacher.PilotEvaluationsPerScenario, ...
    'PFCMLConfig:InvalidRegressionRowGate', ...
    'The regression-row gate must fit inside the pilot budget.');

assert(cfg.Teacher.BoundaryHitRelativeTolerance > 0.0 && ...
       cfg.Teacher.BoundaryHitRelativeTolerance < 0.10 && ...
       cfg.Teacher.MaximumBoundaryHitFractionForTraining >= 0.0 && ...
       cfg.Teacher.MaximumBoundaryHitFractionForTraining <= 1.0, ...
    'PFCMLConfig:InvalidBoundaryGate', ...
    'Stage 6 boundary-gate values are invalid.');

assert(cfg.Teacher.MinimumUniqueTeacherGainPairs >= 2 && ...
       cfg.Teacher.MinimumUniqueTeacherGainPairs <= ...
           cfg.Scenarios.PilotCount && ...
       cfg.Teacher.MinimumTeacherLogSpan > 0.0, ...
    'PFCMLConfig:InvalidDiversityGate', ...
    'Stage 6 teacher-diversity gate values are invalid.');

assert(cfg.Profile.Diagnostic.StartTime_s < ...
       cfg.Profile.Diagnostic.LoadOnTime_s && ...
       cfg.Profile.Diagnostic.LoadOnTime_s < ...
       cfg.Profile.Diagnostic.LoadOffTime_s && ...
       cfg.Profile.Diagnostic.LoadOffTime_s < ...
       cfg.Profile.Diagnostic.StopTime_s, ...
    'PFCMLConfig:InvalidDiagnosticTiming', ...
    'Diagnostic transition times must be strictly increasing.');

assert(cfg.Profile.LongValidation.StartTime_s < ...
       cfg.Profile.LongValidation.LoadOnTime_s && ...
       cfg.Profile.LongValidation.LoadOnTime_s < ...
       cfg.Profile.LongValidation.LoadOffTime_s && ...
       cfg.Profile.LongValidation.LoadOffTime_s < ...
       cfg.Profile.LongValidation.StopTime_s, ...
    'PFCMLConfig:InvalidLongTiming', ...
    'Long-validation transition times must be strictly increasing.');

assert(cfg.Load.NominalPreLoad_W < ...
       cfg.Load.NominalHighLoad_W, ...
    'PFCMLConfig:InvalidNominalLoadStep', ...
    'Nominal high load must exceed nominal pre-load.');

assert(cfg.Load.ScenarioPreLoadRange_W(2) + ...
       cfg.Load.MinimumLoadStep_W <= ...
       cfg.Load.ScenarioHighLoadRange_W(2), ...
    'PFCMLConfig:ImpossibleLoadScenarioRange', ...
    'Load ranges cannot satisfy the required minimum load step.');

assert(abs(sum(cfg.Scenarios.SplitFractions) - 1.0) < 1e-12, ...
    'PFCMLConfig:SplitFractionsInvalid', ...
    'Train/validation/test fractions must sum to 1.0.');

assert(cfg.Scenarios.ForbidRowWiseRandomSplit && ...
       cfg.Scenarios.RequireDisjointScenarioIDs, ...
    'PFCMLConfig:DataLeakageProtectionDisabled', ...
    'Scenario-grouped split and disjoint ScenarioIDs are mandatory.');

forbiddenPredictors = string({ ...
    'Objective'; ...
    'TeacherBestKP'; ...
    'TeacherBestKI'; ...
    'TeacherBestObjective'; ...
    'DeltaLogKP'; ...
    'DeltaLogKI'; ...
    'ScenarioID'; ...
    'RunID'; ...
    'ErrorIdentifier'; ...
    'ErrorMessage'});

leakingPredictors = intersect( ...
    cfg.Data.StudentPredictorColumns, ...
    forbiddenPredictors);

assert(isempty(leakingPredictors), ...
    'PFCMLConfig:PredictorLeakageDetected', ...
    'Forbidden predictor leakage detected: %s', ...
    char(strjoin(leakingPredictors, ', ')));

stage7LeakingPredictors = intersect( ...
    cfg.Stage7.PredictorNames, forbiddenPredictors);

assert(isempty(stage7LeakingPredictors), ...
    'PFCMLConfig:Stage7PredictorLeakageDetected', ...
    'Forbidden Stage 7 predictor leakage detected: %s', ...
    char(strjoin(stage7LeakingPredictors, ', ')));

assert(~any(cfg.Student.CandidateModels == ...
        "LargeNeuralNetwork"), ...
    'PFCMLConfig:UnjustifiedLargeNetwork', ...
    'A large neural network is not justified for this tabular dataset.');

assert(~cfg.Teacher.UseParallel, ...
    'PFCMLConfig:UnsafeParallelExecution', ...
    'Parallel execution remains disabled until explicitly proven safe.');

end
