function verification = verify_pfc_stage12_package()
%VERIFY_PFC_STAGE12_PACKAGE Read-only package and artifact verification.
%
% This function does not run Simulink and does not update the ML model.
%
% Revision: 2.1.0

cfg = pfc_ml_config();
scriptFolder = fileparts(mfilename('fullpath'));
requiredFiles = string({ ...
    'Boost_PFC_BayesOpt_v1_WORKING_BASELINE.slx'; ...
    'pfc_ml_config.m'; ...
    'run_single_pfc_case.m'; ...
    'predict_pfc_stage12_gains.m'; ...
    'run_pfc_stage12_final_hybrid_tuner.m'; ...
    'launch_pfc_ml_dashboard.m'; ...
    'compare_pfc_stage12_controllers.m'; ...
    'build_pfc_stage12_operating_map.m'; ...
    fullfile('pfc_ml_outputs_stage11_prequential_v200', ...
        'pfc_ml_stage11_final_summary.mat')});

for index = 1:numel(requiredFiles)
    fullPath = fullfile(scriptFolder, requiredFiles(index));

    if ~isfile(fullPath)
        error( ...
            'PFCMLStage12:PackageFileMissing', ...
            'Required package file is missing: %s', char(fullPath));
    end
end

runnerText = fileread(fullfile(scriptFolder, 'run_single_pfc_case.m'));
predictorText = fileread( ...
    fullfile(scriptFolder, 'predict_pfc_stage12_gains.m'));
tunerText = fileread( ...
    fullfile(scriptFolder, 'run_pfc_stage12_final_hybrid_tuner.m'));
dashboardText = fileread( ...
    fullfile(scriptFolder, 'launch_pfc_ml_dashboard.m'));
comparisonText = fileread( ...
    fullfile(scriptFolder, 'compare_pfc_stage12_controllers.m'));
mapText = fileread( ...
    fullfile(scriptFolder, 'build_pfc_stage12_operating_map.m'));
assert(contains(runnerText, 'Runner revision: 1.6.0'), ...
    'PFCMLStage12:RunnerRevisionMismatch', ...
    'run_single_pfc_case revision is not 1.6.0.');
assert(contains(predictorText, 'Revision: 2.1.0'), ...
    'PFCMLStage12:PredictorRevisionMismatch', ...
    'Stage 12 predictor revision is not 2.1.0.');
assert(contains(tunerText, 'Revision: 2.1.0'), ...
    'PFCMLStage12:TunerRevisionMismatch', ...
    'Stage 12 tuner revision is not 2.1.0.');
assert(contains(dashboardText, 'Revision: 2.2.3-light'), ...
    'PFCMLStage12:DashboardRevisionMismatch', ...
    'PFC ML dashboard revision is not 2.2.3-light.');
assert(contains(comparisonText, 'Revision: 2.2.1'), ...
    'PFCMLStage12:ComparisonRevisionMismatch', ...
    'PFC ML controller comparison revision is not 2.2.1.');
assert(contains(mapText, 'Revision: 2.2.0'), ...
    'PFCMLStage12:MapRevisionMismatch', ...
    'PFC ML operating map revision is not 2.2.0.');
assert(contains(dashboardText, 'mapImage.AlphaData') && ...
       contains(dashboardText, 'mapAxes.XTick =') && ...
       contains(dashboardText, 'gray x = abstained'), ...
    'PFCMLStage12:OperatingMapDisplayGuardMissing', ...
    ['The operating map must mask abstained cells and show explicit ' ...
     'high-load axis ticks.']);

modelFile = fullfile(scriptFolder, cfg.Model.File);
modelHash = calculateSHA256(modelFile);
assert(strcmpi(modelHash, cfg.Model.ExpectedSHA256), ...
    'PFCMLStage12:BaselineHashMismatch', ...
    'The protected baseline SLX SHA-256 does not match the configuration.');

summaryFile = fullfile( ...
    scriptFolder, 'pfc_ml_outputs_stage11_prequential_v200', ...
    'pfc_ml_stage11_final_summary.mat');
loaded = load(summaryFile, 'output');
assert(isfield(loaded, 'output'), ...
    'PFCMLStage12:Stage11OutputMissing', ...
    'The final summary MAT file has no output variable.');
assert(string(loaded.output.Stage11Revision) == "2.0.0", ...
    'PFCMLStage12:Stage11RevisionMismatch', ...
    'Stage 11 revision must be 2.0.0.');
assert(logical(loaded.output.Summary.OverallPass), ...
    'PFCMLStage12:Stage11OverallPassMissing', ...
    'Stage 11 OverallPass is false.');
assert(~logical(loaded.output.SyntheticOutputsUsed) && ...
       ~logical(loaded.output.Summary.SyntheticOutputsUsed), ...
    'PFCMLStage12:SyntheticOutputDetected', ...
    'The Stage 11 summary reports synthetic outputs.');

probe = struct();
probe.ScenarioID = "STAGE12_READ_ONLY_PROBE";
probe.Vin_RMS = 205.0;
probe.Pload_Pre_W = 350.0;
probe.Pload_High_W = 1300.0;
probe.BoostInductance_uH = 305.0;
probe.DCBusCapacitance_uF = 1250.0;
probe.LineFrequency_Hz = 49.5;
prediction = predict_pfc_stage12_gains(probe);
assert(~prediction.SimulationExecuted && ...
       ~prediction.ResultVerified && ...
       ~prediction.ModelUpdated && ...
       ~prediction.SyntheticOutputsUsed, ...
    'PFCMLStage12:ReadOnlyProbeContractFailed', ...
    'The read-only predictor contract failed.');

verification = struct();
verification.Stage12Revision = "2.1.0";
verification.WorkbenchRevision = "2.2.3-light";
verification.ConfigVersion = string(cfg.Project.ConfigVersion);
verification.BaselineSHA256 = string(modelHash);
verification.Stage11OverallPass = true;
verification.Stage11SyntheticOutputsUsed = false;
verification.ReadOnlyPredictionDecision = prediction.Decision;
verification.SimulationExecuted = false;
verification.ModelModified = false;
verification.ModelUpdated = false;
verification.OverallPass = true;

fprintf('\n');
fprintf('====================================================\n');
fprintf('PFC ML STAGE 12 - PACKAGE VERIFICATION: PASS\n');
fprintf('====================================================\n');
fprintf('Config version       : %s\n', cfg.Project.ConfigVersion);
fprintf('Runner revision      : 1.6.0\n');
fprintf('Stage 12 revision    : 2.1.0\n');
fprintf('Workbench revision   : 2.2.3-light\n');
fprintf('Controller comparison: PASS (real Simulink metrics)\n');
fprintf('Operating map        : PASS (prediction-only label)\n');
fprintf('Baseline SHA-256     : PASS\n');
fprintf('Stage 11 benchmark   : OVERALL PASS\n');
fprintf('Synthetic outputs    : 0\n');
fprintf('Read-only ML probe   : %s\n', char(prediction.Decision));
fprintf('Simulation executed  : NO\n');
fprintf('Model modified       : NO\n');
fprintf('====================================================\n');

end


function hash = calculateSHA256(filePath)

fileIdentifier = fopen(filePath, 'rb');

if fileIdentifier < 0
    error( ...
        'PFCMLStage12:FileReadFailed', ...
        'Could not open file for SHA-256: %s', filePath);
end

fileCleanup = onCleanup(@() fclose(fileIdentifier));
fileBytes = fread(fileIdentifier, Inf, '*uint8');
clear fileCleanup;

digest = java.security.MessageDigest.getInstance('SHA-256');
digest.update(typecast(fileBytes(:), 'int8'));
rawHash = typecast(digest.digest(), 'uint8');
hash = lower(reshape(dec2hex(rawHash, 2).', 1, []));

end
